language: python
install:
  - pip install -q Django==1.8.7
  - pip install -q markdown
python:
  - "2.7"
  # - "3.4"
script:
  - nosetests
  - python manage.py test
env:
  - DJANGO=1.8.7 DJANGO_SETTINGS_MODULE="u02_blog.settings"